## class(day-34:2-7-20)

### Importing Libraries:

In [1]:
import pandas as pd
import numpy as np

### Reading the data:

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",encoding='latin-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
data.shape

(5572, 5)

### splitting the data:

In [5]:
# split the data
# 80% of the data will be in training data  20% of the data will be in testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.v2,data.v1,test_size = 0.2)

In [6]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4457,)
(4457,)
(1115,)
(1115,)


### initialising count vectorizer:

In [7]:
# count vectorizer
from sklearn.feature_extraction.text import CountVectorizer

# creating an object for countvectorizer
count_vect = CountVectorizer()

### To get the feature names:

In [8]:
# generate the word counts for the words in the documents
word_count_vector = count_vect.fit(x_train)

# to get the feature names
word_count_vector.get_feature_names()

['00',
 '000',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '0578',
 '06',
 '07008009200',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '078',
 '07808247860',
 '07808726822',
 '07821230901',
 '07880867867',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081560665',
 '083',
 '0844',
 '08448714184',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '087016248',
 '08701752560',
 '

### Transforming the data:

In [9]:
doc_array = word_count_vector.transform(x_train)
doc_array

<4457x7707 sparse matrix of type '<class 'numpy.int64'>'
	with 58799 stored elements in Compressed Sparse Row format>

In [10]:
# converting to a array
doc_array = word_count_vector.transform(x_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Specifying column names:

In [11]:
# converting the array into a dataframe
pd.DataFrame(doc_array)

0     1     2     3     4     5     6     7     8     9     ...  7697  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4452     0     0     0     0     0     0     0     0     0     0  ...     0   
4453     0     0     0     0     0     0     0     0     0     0  ...     0   
4454     0     0     0     0     0     0     0     0     0     0  ...     0   
4455     0     0     0     0     0     0     0     0     0     0  ...     0   
4456     0     0     0     0     0     0     0     0     0     0  ...     0   

      7698  7699  7700  7701  7702  7703  7704  7705  7706  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4452     0     0     0     0     0     0     0     0     0  
4453     0     0     0     0     0     0     0     0     0  
4454     0     0     0     0     0     0     0     0     0  
4455     0     0     0     0     0     0     0     0     0  
4456     0     0     0     0     0     0     0     0     0  

[4457 rows x 7707 columns]

In [12]:
feature_matrix = pd.DataFrame(doc_array,columns= word_count_vector.get_feature_names())
feature_matrix

00  000  008704050406  0089  0121  01223585236  01223585334  0125698789  \
0      0    0             0     0     0            0            0           0   
1      0    0             0     0     0            0            0           0   
2      0    0             0     0     0            0            0           0   
3      0    0             0     0     0            0            0           0   
4      0    0             0     0     0            0            0           0   
...   ..  ...           ...   ...   ...          ...          ...         ...   
4452   0    0             0     0     0            0            0           0   
4453   0    0             0     0     0            0            0           0   
4454   0    0             0     0     0            0            0           0   
4455   0    0             0     0     0            0            0           0   
4456   0    0             0     0     0            0            0           0   

      02  0207  ...  ìä  ìï  û_  û_thanks  ûªm  ûªt  ûªve  ûï  ûïharry  ûò  
0      0     0  ...   0   0   0         0    0    0     0   0        0   0  
1      0     0  ...   0   0   0         0    0    0     0   0        0   0  
2      0     0  ...   0   0   0         0    0    0     0   0        0   0  
3      0     0  ...   0   0   0         0    0    0     0   0        0   0  
4      0     0  ...   0   0   0         0    0    0     0   0        0   0  
...   ..   ...  ...  ..  ..  ..       ...  ...  ...   ...  ..      ...  ..  
4452   0     0  ...   0   0   0         0    0    0     0   0        0   0  
4453   0     0  ...   0   0   0         0    0    0     0   0        0   0  
4454   0     0  ...   0   0   0         0    0    0     0   0        0   0  
4455   0     0  ...   0   0   0         0    0    0     0   0        0   0  
4456   0     0  ...   0   0   0         0    0    0     0   0        0   0  

[4457 rows x 7707 columns]

In [13]:
# pd.set_option('display.max_rows',None)

## class(day-35:3-7-20)

In [14]:
# TFIDF Vectorizer
# Import TfIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize and object for the TFIDF Vectorizer
tfidf = TfidfVectorizer()

In [15]:
# apply the tfidf to the data(x_train)
x_train_transformed = tfidf.fit_transform(x_train)
x_train_transformed

<4457x7707 sparse matrix of type '<class 'numpy.float64'>'
	with 58799 stored elements in Compressed Sparse Row format>

In [16]:
x_test_transformed = tfidf.transform(x_test)
x_test_transformed

<1115x7707 sparse matrix of type '<class 'numpy.float64'>'
	with 14060 stored elements in Compressed Sparse Row format>

In [17]:
# Feature Names
tfidf.get_feature_names()

['00',
 '000',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '0578',
 '06',
 '07008009200',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '078',
 '07808247860',
 '07808726822',
 '07821230901',
 '07880867867',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081560665',
 '083',
 '0844',
 '08448714184',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701213186',
 '08701237397',
 '08701417012',
 '08701417012150p',
 '087016248',
 '08701752560',
 '

### Vocabulary Position:

In [18]:
# position of the words in the sparse matrix
tfidf.vocabulary_

{'india': 3626,
 'going': 3136,
 'to': 6886,
 'draw': 2416,
 'the': 6775,
 'series': 5995,
 'after': 835,
 'many': 4314,
 'years': 7628,
 'in': 3602,
 'south': 6315,
 'african': 833,
 'soil': 6256,
 'spook': 6366,
 'up': 7129,
 'your': 7659,
 'mob': 4513,
 'with': 7494,
 'halloween': 3269,
 'collection': 1885,
 'of': 4856,
 'logo': 4142,
 'pic': 5168,
 'message': 4424,
 'plus': 5227,
 'free': 2949,
 'eerie': 2514,
 'tone': 6911,
 'txt': 7044,
 'card': 1642,
 '8007': 620,
 'zed': 7683,
 '08701417012150p': 69,
 'per': 5116,
 'do': 2349,
 'you': 7653,
 'always': 918,
 'celebrate': 1691,
 'ny': 4831,
 'family': 2740,
 'don': 2381,
 'look': 4157,
 'back': 1187,
 'at': 1104,
 'building': 1545,
 'because': 1273,
 'have': 3322,
 'no': 4762,
 'coat': 1863,
 'and': 947,
 'want': 7324,
 'get': 3083,
 'more': 4552,
 'sick': 6120,
 'just': 3839,
 'hurry': 3522,
 'home': 3437,
 'wear': 7369,
 'gym': 3251,
 'entry': 2592,
 'into': 3678,
 'our': 4970,
 '250': 359,
 'weekly': 7391,
 'comp': 1911,
 'sen

In [19]:
# Idf of the terms
tfidf.idf_

array([7.61069604, 6.35793308, 8.70930833, ..., 8.70930833, 8.70930833,
       7.7930176 ])

In [20]:
# Apply the naive Bayes Algorithm
# Import BernNB
from sklearn.naive_bayes import BernoulliNB
# creating an object for BerNB
model_BernNB = BernoulliNB()

In [21]:
# Applying the algorithm to the data
# objectName.fit(Input,Output)
model_BernNB.fit(x_train_transformed, y_train) 

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [24]:
# prediction on test data
# SYNTAX: objectname.predict(InputValues)
y_test_pred = model_BernNB.predict(x_test_transformed)

In [25]:
# compare the actual values(y_test) with predicted values(y_test_pred)
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_test_pred)

array([[954,   0],
       [ 22, 139]], dtype=int64)

In [26]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       954
        spam       1.00      0.86      0.93       161

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.96      1115
weighted avg       0.98      0.98      0.98      1115



### Testing for new message

In [30]:
# test a single message --> Spam or Ham
new_message = pd.Series('Last few days to collect the free entry passes with 40% discount')
#calculate tfidf values for the new message
new_message_transformed = tfidf.transform(new_message)

In [31]:
# predict the new message
model_BernNB.predict(new_message_transformed)

array(['ham'], dtype='<U4')